language: node_js
node_js:
  - "0.12"
after_script:
  - npm run coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#bionode"
    template:
      - "%{message} %{repository}#%{build_number}: %{commit_message} (%{branch} - %{commit} : %{author})"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc08fdd81e88a4b24fed
    on_success: change
    on_failure: always
    on_start: false
  env: DEBUG='*'
